config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :users
  resources :events
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attended_event, class_name: :Event, foreign_key: :event_id
  belongs_to :attendee, class_name: :User
  validates :event_id, presence: true
  validates :attendee_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  belongs_to :creator, class_name: :User
  has_many :attendees, class_name: :User, through: :attendances
  validates :description, presence: true
  validates :scheduled, presence: true

  scope :upcoming, -> { where("scheduled >= date('now')") }
  scope :previous, -> { where("scheduled <  date('now')") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :events, foreign_key: 'creator_id', dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :attended_events, through: :attendances
  validates :name, presence: true, length: { maximum: 60 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception

  def current_user
    return nil unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user=(user)
    if user
      session[:user_id] = user.id
    else
      session.delete :user_id
    end
    @current_user = user || nil
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in'
    redirect_to login_url
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :current_user
  before_action :logged_in_user, only: %i[create new]

  def index
    @events = Event.all
    @upcoming = @events.upcoming
    @previous = @events.previous
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      @event.attendees << current_user
      flash[:success] = 'Event Created!'
      redirect_to @event
    else
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description,
                                  :location, :scheduled)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :current_user

  def new; end

  def create
    if (self.current_user = User.find_by(email: params[:session][:email]))
      flash[:success] = 'You are succesffully loged in.'
      redirect_to current_user
    else
      flash.now[:failure] = 'Invalid username. Please try again.'
      render :new
    end
  end

  def destroy
    self.current_user = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user
  before_action :logged_in_user, only: %i[show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Sample App!'
      self.current_user = @user
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.attended_events
    @previous = @user.attended_events.previous
    @upcoming = @user.attended_events.upcoming
  end

  private

  def user_params
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !@current_user.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li>
  <%= link_to event.description, event %> 
</li>

app/views/events/index.html.erb
<h1>Events</h1>
<% if @upcoming.count < 1 && @previous.count <1 %>
  <h2>No events created</h2>
  <%= link_to 'Create a new event', new_event_path %>
<% end %>
<% if @upcoming.count > 0 %>
  <h2>Upcoming</h2>
  <% @upcoming.each do |event| %>
      <%= render 'events/event', event: event %>
  <% end %>
<% end %>
<% if @previous.count > 0 %>
  <h2>Previous</h2>
  <% @previous.each do |event| %>
    <%= render 'events/event', event: event %>
  <% end %>
<% end %>

app/views/events/new.html.erb
<% if @event && @event.errors.any? %>
  The form contains <%= pluralize(@event.errors.count, "error") %>.
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(:event, url: events_path) do |f| %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :scheduled %>
  <%= f.datetime_field :scheduled %>
  <br>
  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<p>
  <strong>Scheduled: </strong>
  <%= @event.scheduled %>
</p>
<% if @event.attendees.count > 0 %>
  <ul> <strong>Attendees</strong>
    <% @event.attendees.each do |x| %>
      <li>
        <%= link_to x.name, x %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Events', events_path %></li>
      <% if logged_in? %>
        <li><%= link_to 'User Profile', @current_user %></li>
        <li><%= link_to 'New event', new_event_path %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Signup', signup_path %></li>
      <% end %>
    </ul>
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  The form contains <%= pluralize(@user.errors.count, "error") %>.
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(:user, url: users_path) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if @user.events.count > 0 %>
<ul>
  <strong>Created events by <%= @user.name %></strong>
  <%= render @events %>
</ul>
<% end %>

<% if @user.attended_events.count > 0 %>
<ul>
  <strong>Attended events</strong><br>
  <li>
    <strong>Upcoming events</strong>
  </li>
  <ul>
    <% @upcoming.each do |x| %>
    <li>
      <%= link_to x.description, x %>
    </li>
    <% end %>
  </ul>
  <li>
    <strong>Previously attended events</strong>
  </li>
  <ul>
    <% @previous.each do |x| %>
    <li>
      <%= link_to x.description, x %>
    </li>
    <% end %>
  </ul>
</ul>
<% end %>